### ISSUE TITLE
启动容器进行自助测试时，发现两个问题：

### ISSUE THREAD

**Issue by pengyulong** [nelivacn/FAT#3]
根据文档的操作步骤
![1691132746945](https://github.com/nelivacn/FAT/assets/9189026/de12fbc0-31e3-4dc6-81e9-10a079c047ca)

启动容器与测试服务时发现两个问题:
1.启动容器时，会出现"docker: Error response from daemon: No command specified.",经检查发现，未指定要在容器中运行的命令，在最后加上/bin/bash后正常；
2.根据
![1691132943968](https://github.com/nelivacn/FAT/assets/9189026/9123ddfc-3617-4a11-9ce4-c365ccb8af27) 发现会报错，经检查发现停的my.sh脚本换行符是window系统下的。

**Comment by msbrm** [comment]
1. 报错不影响
2. 检查是否在Windows系统上克隆的项目
