### ISSUE TITLE
启动测试服务的时候报错，看日志像是kafka启动失败，换了端口后，还是启动失败。

### ISSUE THREAD

**Issue by pengyulong** [nelivacn/FAT#4]
hi,我启动容器进行测试后，发现两个测试结构都无响应，看了下服务启动的日志，出现kafka启动失败，请问这个应该怎么处理，是配置的端口不对吗？还是依赖什么组件？
![1691139159525](https://github.com/nelivacn/FAT/assets/9189026/235fe209-19cb-4bf8-9fac-988f2c163f01)

**Comment by msbrm** [comment]
kafka 相关报错不影响 接口功能验证
